### ISSUE TITLE
Do not support log file size control and rotate?

### ISSUE THREAD

**Issue by cybfly** [kataras/golog#10]
I am using iris and use golog with it.
I followed the demo to add a file output like the codes below.
But it seems we can not control the size of the log file, and log rotate?
Does golog support this?

       func testLog() {
	file, err := os.OpenFile(".\app.log", os.O_APPEND|os.O_CREATE, 0755)
	if err != nil {
		panic("failed to open log file")
	}
	defer file.Close()
       golog.AddOutput(file)

	golog.Handle(func(l *golog.Log) bool {
		prefix := golog.GetTextForLevel(l.Level, false)
		pc, fn, line, _ := runtime.Caller(7)
		message := fmt.Sprintf("%s [%s] [%s %s %d]: %s",
			prefix, l.FormatTime(), fn, runtime.FuncForPC(pc).Name(), line, l.Message)

		if l.NewLine {
			message += "\n"
		}

		fmt.Print(message)
		file.WriteString(message)
		return true
	})

	golog.ErrorText("{ERR}", "\x1b[32m[ERR]\x1b[0m")
	golog.Warnf("Hey, warning here")
	golog.Errorf("Something went wrong!")
}

**Comment by xleyba** [comment]
Hi

As per what I have read in other loggers, that is function that should be implemented outside your go application, at least if performance matters for you.

There are other tools that could rotate logs without impacting in your application performance.
Also, bear in mind that Dockers and centralized logs are trending topic these days so people normally is using tools like filebit to send logs to Logstash/Elastic on the fly and then nobody cares on log file rolling.

Just an opinion from a go rookie . :)

Regards
J

**Comment by kataras** [comment]
Hello, check an example: https://github.com/kataras/golog/blob/master/_examples/rotation/main.go
