### ISSUE TITLE
Log rotate?

### ISSUE THREAD

**Issue by BingerYuan** [kataras/golog#16]

**Comment by kataras** [comment]
Log rotation is not part of `golog` but what stops you from doing it by yourself? I think there are enough tools that takes the input of `golog` and can perform log rotation but if they are not fulfill your needs please ask for specific features of log rotation that you need so I can start coding them.

Thanks and sorry for the delay @BingerYuan

**Comment by kataras** [comment]
See example: https://github.com/kataras/golog/blob/master/_examples/rotation/main.go
