### ISSUE TITLE
InstallStd print file location error

### ISSUE THREAD

**Issue by icoder528** [kataras/golog#4]
`golog.InstallStd(log.New(os.Stderr, "", log.LstdFlags|log.Lshortfile))`

get print location always in `integration.go:79`

**Comment by kataras** [comment]
Yes, you have to customize the output (look here: https://github.com/kataras/golog/issues/3#issuecomment-355895870) but look at the `runtime.Caller(6)` , change it to 7 or 8 and play with it until you make it to print the location of your source code instead of the golog's integration.
